FINALLY: workflow in github actions

diff --git a/.github/workflows/prod.yaml b/.github/workflows/prod.yaml
--- a/.github/workflows/prod.yaml
+++ b/.github/workflows/prod.yaml
@@ -20,44 +20,45 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          # Adicionar chave SSH
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ec2-54-232-19-163.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts
-
-          # Conectar via SSH e executar os comandos
-          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-232-19-163.sa-east-1.compute.amazonaws.com << 'EOF'
-            # Verificar se o diretório existe
-            if [ ! -d "portifolioreact" ]; then
-              echo "Directory portifolioreact does not exist!"
-              exit 1
-            fi
-
-            # Navegar para o diretório e fazer git pull
-            cd portifolioreact
-            git pull
-
-            # Verificar se o Docker está instalado
-            if ! command -v docker &> /dev/null
-            then
-                echo "Docker not found, installing..."
-                sudo apt-get update
-                sudo apt-get install -y docker.io
-            fi
-
-            # Verificar se o Docker Compose está instalado
-            if ! command -v docker-compose &> /dev/null
-            then
-                echo "Docker Compose not found, installing..."
-                sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-                sudo chmod +x /usr/local/bin/docker-compose
-            fi
-
-            # Parar e remover containers, e reconstruir/levantar novamente
-            docker compose down -v
-            docker compose up -d --build
-
-            # Exibir logs do Docker
-            docker-compose logs
-          EOF
+            # Adicionar chave SSH
+            mkdir -p ~/.ssh
+            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+            chmod 600 ~/.ssh/id_rsa
+            ssh-keyscan -H ec2-54-232-19-163.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts
+        
+            # Conectar via SSH e executar os comandos
+            ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-232-19-163.sa-east-1.compute.amazonaws.com << 'EOF'
+              # Verificar se o diretório existe
+              if [ ! -d "portifolioreact" ]; then
+                echo "Directory portifolioreact does not exist!"
+                exit 1
+              fi
+        
+              # Navegar para o diretório e fazer git pull
+              cd portifolioreact
+              git pull
+        
+              # Verificar se o Docker está instalado
+              if ! command -v docker &> /dev/null
+              then
+                  echo "Docker not found, installing..."
+                  sudo apt-get update
+                  sudo apt-get install -y docker.io
+              fi
+        
+              # Verificar se o Docker Compose está instalado
+              if ! command -v docker-compose &> /dev/null
+              then
+                  echo "Docker Compose not found, installing..."
+                  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                  sudo chmod +x /usr/local/bin/docker-compose
+              fi
+        
+              # Parar e remover containers, e reconstruir/levantar novamente
+              docker compose down -v
+              docker compose up -d --build
+        
+              # Exibir logs do Docker
+              docker-compose logs
+            EOF
+        
